# Kubernetes deployment and service for Django + Gunicorn
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django
          image: gcr.io/skyline-soaring-storage/skylinesoaring:latest
          ports:
            - containerPort: 8000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/skyline-soaring-storage.json
          envFrom:
            - secretRef:
                name: manage2soar-env
          volumeMounts:
            - name: static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media
            - name: gcp-sa-key
              mountPath: /app/skyline-soaring-storage.json
              subPath: skyline-soaring-storage.json
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: static-files
          emptyDir: {}
        - name: media-files
          emptyDir: {}
        - name: gcp-sa-key
          secret:
            secretName: gcp-sa-key
---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
